In [13]:
import numpy as np
f=np.poly1d([1,-5,6])
print(f)

   2
1 x - 5 x + 6


In [14]:
np.poly1d(a,True)

poly1d([ 1., -5.,  6.])

In [15]:
f.c

array([ 1, -5,  6])

In [16]:
f.order

2

In [17]:
f[1]

-5

In [18]:
f*f

poly1d([  1, -10,  37, -60,  36])

In [21]:
(f*f).r

array([3.+3.15149730e-07j, 3.-3.15149730e-07j, 2.+2.40875514e-07j,
       2.-2.40875514e-07j])

In [20]:
b.r

array([3.+3.15149730e-07j, 3.-3.15149730e-07j, 2.+2.40875514e-07j,
       2.-2.40875514e-07j])